/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.test.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-10-2015
 * 
 * XDoclet definition:
 * @struts.form name="endForm"
 */
public class EndForm extends ActionForm {
    /*
     * Generated fields
     */

    /** end property */
    private String end;

    /*
     * Generated Methods
     */

    /** 
     * Method validate
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
            HttpServletRequest request) {
        // TODO Auto-generated method stub
        return null;
    }

    /** 
     * Method reset
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
    }

    /** 
     * Returns the end.
     * @return String
     */
    public String getEnd() {
        return end;
    }

    /** 
     * Set the end.
     * @param end The end to set
     */
    public void setEnd(String end) {
        this.end = end;
    }
}